import { describe, it, expect, vi, beforeEach } from "vitest";
import type { Logger, TrackerPlugin } from "@ultracoder/core";
import { runDualAssessment, type DualAssessorConfig } from "./dual-assessor.js";
import type { AgentAssessment, IssueRecord } from "./types.js";
import * as assessorModule from "./assessor.js";

vi.mock("./assessor.js", () => ({
	runAssessment: vi.fn(),
}));

function makeLogger(): Logger {
	return {
		debug: vi.fn(),
		info: vi.fn(),
		warn: vi.fn(),
		error: vi.fn(),
		child: vi.fn().mockReturnThis(),
	};
}

function makeRecord(overrides: Partial<IssueRecord> = {}): IssueRecord {
	return {
		issueId: "42",
		issueUrl: "https://github.com/test/repo/issues/42",
		title: "Bug in auth",
		body: "Login fails when...",
		state: "assessing",
		firstSeenAt: new Date().toISOString(),
		lastCheckedAt: new Date().toISOString(),
		...overrides,
	};
}

function makeAssessment(agent: string, overrides: Partial<AgentAssessment> = {}): AgentAssessment {
	return {
		agent,
		severity: "high",
		effort: "small",
		rootCause: "Missing null check",
		proposedFix: "Add guard clause",
		relatedFiles: ["src/auth.ts"],
		confidence: 0.85,
		completedAt: new Date().toISOString(),
		...overrides,
	};
}

function makeTracker(opts: { addComment?: boolean } = {}): TrackerPlugin {
	const tracker: TrackerPlugin = {
		meta: { name: "test-tracker", slot: "tracker", version: "0.0.1" },
		createIssue: vi.fn(),
		updateIssue: vi.fn(),
		getIssue: vi.fn(),
		listIssues: vi.fn(),
	};
	if (opts.addComment !== false) {
		tracker.addComment = vi.fn().mockResolvedValue("comment-123");
	}
	return tracker;
}

const defaultConfig: DualAssessorConfig = {
	claudeConfig: { agentPath: "claude", timeoutMs: 30000 },
	codexConfig: { agentPath: "codex", timeoutMs: 30000 },
};

describe("runDualAssessment", () => {
	beforeEach(() => {
		vi.clearAllMocks();
	});

	it("runs both assessments in parallel and returns results", async () => {
		const claudeAssessment = makeAssessment("claude-opus-4-6");
		const codexAssessment = makeAssessment("codex", { severity: "medium", confidence: 0.7 });

		vi.mocked(assessorModule.runAssessment)
			.mockResolvedValueOnce(claudeAssessment)
			.mockResolvedValueOnce(codexAssessment);

		const result = await runDualAssessment(
			makeRecord(),
			defaultConfig,
			makeTracker(),
			makeLogger(),
		);

		expect(result.claude).toEqual({ ...claudeAssessment, commentId: "comment-123" });
		expect(result.codex).toEqual({ ...codexAssessment, commentId: "comment-123" });
		expect(assessorModule.runAssessment).toHaveBeenCalledTimes(2);
	});

	it("posts assessment comments to GitHub via tracker.addComment", async () => {
		vi.mocked(assessorModule.runAssessment)
			.mockResolvedValueOnce(makeAssessment("claude-opus-4-6"))
			.mockResolvedValueOnce(makeAssessment("codex"));

		const tracker = makeTracker();
		await runDualAssessment(makeRecord(), defaultConfig, tracker, makeLogger());

		expect(tracker.addComment).toHaveBeenCalledTimes(2);
		const calls = vi.mocked(tracker.addComment!).mock.calls;
		expect(calls[0][0]).toBe("42");
		expect(calls[0][1]).toContain("Assessment by claude-opus-4-6");
		expect(calls[1][1]).toContain("Assessment by codex");
	});

	it("comment includes severity, effort, confidence, root cause, and related files", async () => {
		const assessment = makeAssessment("claude-opus-4-6", {
			severity: "critical",
			effort: "large",
			confidence: 0.95,
			rootCause: "SQL injection in query builder",
			proposedFix: "Use parameterized queries",
			relatedFiles: ["src/db.ts", "src/query.ts"],
		});
		vi.mocked(assessorModule.runAssessment)
			.mockResolvedValueOnce(assessment)
			.mockResolvedValueOnce(makeAssessment("codex"));

		const tracker = makeTracker();
		await runDualAssessment(makeRecord(), defaultConfig, tracker, makeLogger());

		const comment = vi.mocked(tracker.addComment!).mock.calls[0][1];
		expect(comment).toContain("**Severity:** critical");
		expect(comment).toContain("**Effort:** large");
		expect(comment).toContain("**Confidence:** 0.95");
		expect(comment).toContain("SQL injection in query builder");
		expect(comment).toContain("Use parameterized queries");
		expect(comment).toContain("`src/db.ts`");
		expect(comment).toContain("`src/query.ts`");
		expect(comment).toContain("Generated by Ultracoder issue monitor");
	});

	it("degrades gracefully when Claude fails — returns Codex only", async () => {
		const codexAssessment = makeAssessment("codex");
		vi.mocked(assessorModule.runAssessment)
			.mockRejectedValueOnce(new Error("Claude timeout"))
			.mockResolvedValueOnce(codexAssessment);

		const logger = makeLogger();
		const result = await runDualAssessment(
			makeRecord(),
			defaultConfig,
			makeTracker(),
			logger,
		);

		expect(result.claude).toBeUndefined();
		expect(result.codex).toBeDefined();
		expect(result.codex!.agent).toBe("codex");
		expect(logger.error).toHaveBeenCalledWith(
			"Claude assessment failed",
			expect.objectContaining({ error: expect.anything() }),
		);
	});

	it("degrades gracefully when Codex fails — returns Claude only", async () => {
		const claudeAssessment = makeAssessment("claude-opus-4-6");
		vi.mocked(assessorModule.runAssessment)
			.mockResolvedValueOnce(claudeAssessment)
			.mockRejectedValueOnce(new Error("Codex unavailable"));

		const logger = makeLogger();
		const result = await runDualAssessment(
			makeRecord(),
			defaultConfig,
			makeTracker(),
			logger,
		);

		expect(result.claude).toBeDefined();
		expect(result.codex).toBeUndefined();
		expect(logger.error).toHaveBeenCalledWith(
			"Codex assessment failed",
			expect.objectContaining({ error: expect.anything() }),
		);
	});

	it("throws when both assessments fail", async () => {
		vi.mocked(assessorModule.runAssessment)
			.mockRejectedValueOnce(new Error("Claude down"))
			.mockRejectedValueOnce(new Error("Codex down"));

		await expect(
			runDualAssessment(makeRecord(), defaultConfig, makeTracker(), makeLogger()),
		).rejects.toThrow("Both assessments failed");
	});

	it("skips posting comments when tracker lacks addComment", async () => {
		vi.mocked(assessorModule.runAssessment)
			.mockResolvedValueOnce(makeAssessment("claude-opus-4-6"))
			.mockResolvedValueOnce(makeAssessment("codex"));

		const tracker = makeTracker({ addComment: false });
		const result = await runDualAssessment(
			makeRecord(),
			defaultConfig,
			tracker,
			makeLogger(),
		);

		expect(result.claude).toBeDefined();
		expect(result.codex).toBeDefined();
		expect(result.claude!.commentId).toBeUndefined();
		expect(result.codex!.commentId).toBeUndefined();
	});

	it("still returns assessment when addComment throws", async () => {
		vi.mocked(assessorModule.runAssessment)
			.mockResolvedValueOnce(makeAssessment("claude-opus-4-6"))
			.mockResolvedValueOnce(makeAssessment("codex"));

		const tracker = makeTracker();
		vi.mocked(tracker.addComment!).mockRejectedValue(new Error("GitHub API 500"));

		const logger = makeLogger();
		const result = await runDualAssessment(
			makeRecord(),
			defaultConfig,
			tracker,
			logger,
		);

		expect(result.claude).toBeDefined();
		expect(result.codex).toBeDefined();
		expect(result.claude!.commentId).toBeUndefined();
		expect(result.codex!.commentId).toBeUndefined();
		expect(logger.warn).toHaveBeenCalledTimes(2);
	});

	it("shows (none identified) when relatedFiles is empty", async () => {
		vi.mocked(assessorModule.runAssessment)
			.mockResolvedValueOnce(makeAssessment("claude-opus-4-6", { relatedFiles: [] }))
			.mockResolvedValueOnce(makeAssessment("codex"));

		const tracker = makeTracker();
		await runDualAssessment(makeRecord(), defaultConfig, tracker, makeLogger());

		const comment = vi.mocked(tracker.addComment!).mock.calls[0][1];
		expect(comment).toContain("(none identified)");
	});

	it("passes correct agent names and configs to runAssessment", async () => {
		vi.mocked(assessorModule.runAssessment)
			.mockResolvedValueOnce(makeAssessment("claude-opus-4-6"))
			.mockResolvedValueOnce(makeAssessment("codex"));

		const record = makeRecord({ issueId: "77", title: "Test bug", body: "Details" });
		await runDualAssessment(record, defaultConfig, makeTracker(), makeLogger());

		const calls = vi.mocked(assessorModule.runAssessment).mock.calls;
		// Claude call
		expect(calls[0][0]).toBe("claude-opus-4-6");
		expect(calls[0][1]).toBe("77");
		expect(calls[0][2]).toBe("Test bug");
		expect(calls[0][3]).toBe("Details");
		expect(calls[0][4]).toEqual(defaultConfig.claudeConfig);
		// Codex call
		expect(calls[1][0]).toBe("codex");
		expect(calls[1][4]).toEqual(defaultConfig.codexConfig);
	});
});
