import type { Logger, TrackerPlugin } from "@ultracoder/core";
import type { AgentAssessment, IssueRecord } from "./types.js";
import { runAssessment, type AssessorConfig } from "./assessor.js";

export interface DualAssessorConfig {
	claudeConfig: AssessorConfig;
	codexConfig: AssessorConfig;
}

/**
 * Format an assessment as a GitHub issue comment.
 */
function formatComment(assessment: AgentAssessment): string {
	const files = assessment.relatedFiles.map((f) => `- \`${f}\``).join("\n");
	return `## Assessment by ${assessment.agent}

**Severity:** ${assessment.severity} | **Effort:** ${assessment.effort} | **Confidence:** ${assessment.confidence}

### Root Cause
${assessment.rootCause}

### Proposed Fix
${assessment.proposedFix}

### Related Files
${files || "- (none identified)"}

---
*Generated by Ultracoder issue monitor*`;
}

/**
 * Run dual assessments (Claude + Codex) in parallel.
 * Posts results as comments on the GitHub issue.
 * Degrades gracefully if one agent fails.
 */
export async function runDualAssessment(
	record: IssueRecord,
	config: DualAssessorConfig,
	tracker: TrackerPlugin,
	logger: Logger,
): Promise<{ claude?: AgentAssessment; codex?: AgentAssessment }> {
	const log = logger.child({ component: "dual-assessor", issueId: record.issueId });

	const [claudeResult, codexResult] = await Promise.allSettled([
		runAssessment(
			"claude-opus-4-6",
			record.issueId,
			record.title,
			record.body,
			config.claudeConfig,
			logger,
		),
		runAssessment(
			"codex",
			record.issueId,
			record.title,
			record.body,
			config.codexConfig,
			logger,
		),
	]);

	const assessments: { claude?: AgentAssessment; codex?: AgentAssessment } = {};

	// Process Claude result
	if (claudeResult.status === "fulfilled") {
		assessments.claude = claudeResult.value;
		if (tracker.addComment) {
			try {
				const commentId = await tracker.addComment(
					record.issueId,
					formatComment(claudeResult.value),
				);
				assessments.claude.commentId = commentId;
			} catch (err) {
				log.warn("Failed to post Claude assessment comment", {
					error: err instanceof Error ? err.message : String(err),
				});
			}
		}
	} else {
		log.error("Claude assessment failed", { error: claudeResult.reason });
	}

	// Process Codex result
	if (codexResult.status === "fulfilled") {
		assessments.codex = codexResult.value;
		if (tracker.addComment) {
			try {
				const commentId = await tracker.addComment(
					record.issueId,
					formatComment(codexResult.value),
				);
				assessments.codex.commentId = commentId;
			} catch (err) {
				log.warn("Failed to post Codex assessment comment", {
					error: err instanceof Error ? err.message : String(err),
				});
			}
		}
	} else {
		log.error("Codex assessment failed", { error: codexResult.reason });
	}

	if (!assessments.claude && !assessments.codex) {
		throw new Error("Both assessments failed");
	}

	log.info("Dual assessment complete", {
		claude: !!assessments.claude,
		codex: !!assessments.codex,
	});

	return assessments;
}
